test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: <%= ENV.fetch("GCS_PROJECT_ID") %>
  credentials:
    type: service_account
    project_id: <%= ENV.fetch("GCS_PROJECT_ID") %>
    private_key_id: <%= ENV.fetch("GCS_PRIVATE_KEY_ID") %>
    private_key: "<%= ENV.fetch('GCS_PRIVATE_KEY').gsub('\\n', '\n') %>"
    client_email: <%= ENV.fetch("GCS_CLIENT_EMAIL") %>
    client_id: <%= ENV.fetch("GCS_CLIENT_ID") %>
  bucket: <%= ENV.fetch("GCS_BUCKET") %>
